"""PostgreSQL connections. DATABASE_URL is required; no file database fallback."""

from __future__ import annotations

import os
import json
import re
from contextlib import contextmanager
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

_data_dir = os.environ.get("DATA_DIR") or os.environ.get("RAILWAY_VOLUME_MOUNT_PATH")
DATA_DIR = Path(_data_dir) if _data_dir else ROOT / "data"
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"

_INSERT_TABLE = re.compile(r"^\s*INSERT(?:\s+OR\s+IGNORE)?\s+INTO\s+(\w+)", re.I)
_ID_TABLES = {
    "households",
    "ingredients",
    "recipes",
    "plans",
    "plan_slots",
    "grocery_lines",
    "pantry_items",
    "household_overrides",
    "prep_tasks",
    "recipe_submissions",
    "users",
    "taste_people",
    "taste_events",
}


def database_url() -> str:
    return (os.environ.get("DATABASE_URL") or "").strip()




class Row:
    def __init__(self, mapping: dict[str, Any]):
        self._data = dict(mapping)
        self._keys = list(mapping.keys())

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._data[self._keys[key]]
        return self._data[key]

    def keys(self):
        return self._data.keys()

    def __iter__(self):
        for k in self._keys:
            yield self._data[k]


class Cursor:
    def __init__(self, rows: list[Row] | None = None, lastrowid: int | None = None):
        self._rows = rows or []
        self.lastrowid = lastrowid
        self._i = 0

    def fetchone(self):
        if self._i >= len(self._rows):
            return None
        row = self._rows[self._i]
        self._i += 1
        return row

    def fetchall(self):
        out = self._rows[self._i :]
        self._i = len(self._rows)
        return out

    def __iter__(self):
        return iter(self.fetchall())


class PgConnection:
    def __init__(self, conn):
        self._conn = conn
        self.lastrowid = None

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        try:
            if exc_type is None: self.commit()
            else: self.rollback()
        finally: self.close()

    def execute(self, sql: str, params: tuple | list = ()):
        sql_pg, returning = _postgres_sql(sql)
        with self._conn.cursor() as cur:
            cur.execute(sql_pg, tuple(params) if params is not None else None)
            lastrowid = None
            rows: list[Row] = []
            if cur.description:
                names = [c.name for c in cur.description]
                fetched = cur.fetchall()
                for raw in fetched:
                    mapping = {names[i]: raw[i] for i in range(len(names))}
                    rows.append(Row(mapping))
                if returning and fetched:
                    lastrowid = fetched[0][0]
                    rows = []
            self.lastrowid = lastrowid
            return Cursor(rows, lastrowid)

    def executescript(self, script: str) -> None:
        for stmt in _split_sql(script):
            if not stmt.strip() or stmt.strip().upper().startswith("PRAGMA"):
                continue
            self.execute(_postgres_schema_stmt(stmt))

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


def _split_sql(script: str) -> list[str]:
    parts = []
    buf = []
    for line in script.splitlines():
        stripped = line.strip()
        if stripped.startswith("--"):
            continue
        buf.append(line)
        if stripped.endswith(";"):
            parts.append("\n".join(buf))
            buf = []
    if buf:
        parts.append("\n".join(buf))
    return [p.strip() for p in parts if p.strip()]


def _postgres_schema_stmt(stmt: str) -> str:
    return stmt.replace(
        "INTEGER PRIMARY KEY",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )


def _postgres_sql(sql: str) -> tuple[str, bool]:
    ignore = bool(re.match(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO", sql, re.I))
    out = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, flags=re.I)
    out = out.replace("date('now')", "CURRENT_DATE")
    out = out.replace("?", "%s")
    out = re.sub(r"ON CONFLICT\(", "ON CONFLICT (", out, flags=re.I)
    if ignore and "ON CONFLICT" not in out.upper():
        out = out.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    m = _INSERT_TABLE.match(sql)
    returning = False
    if m and m.group(1).lower() in _ID_TABLES and "RETURNING" not in out.upper():
        out = out.rstrip().rstrip(";") + " RETURNING id"
        returning = True
    return out, returning


def connect():
    import psycopg
    from psycopg import sql

    url = database_url()
    if not url:
        raise RuntimeError("DATABASE_URL is required. Configure the Railway PostgreSQL URL or a local PostgreSQL test database.")
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://"):]
    conn = psycopg.connect(url, connect_timeout=5)
    schema = os.environ.get("DATABASE_SCHEMA", "public")
    conn.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(schema)))
    conn.commit()
    return PgConnection(conn)


def _add_column(conn, table: str, name: str, spec: str) -> None:
    conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {spec}")


def migrate_prep_completion(conn) -> None:
    """Fold legacy step checks into task JSON before retiring the duplicate table."""
    if not conn.execute("SELECT to_regclass('prep_step_done') AS name").fetchone()["name"]:
        return
    legacy: dict[int, set[str]] = {}
    for row in conn.execute("SELECT plan_id, recipe_id, step_key FROM prep_step_done"):
        legacy.setdefault(row["plan_id"], set()).add(f"{row['recipe_id']}:{row['step_key']}")
    for task in conn.execute("SELECT * FROM prep_tasks"):
        details = json.loads(task["details_json"])
        keys = {f"{meal['id']}:{step['key']}" for meal in details.get("meals", []) for step in meal.get("steps", [])}
        completed = (set(json.loads(task["completed_steps_json"])) | legacy.get(task["plan_id"], set())) & keys
        if task["done"]:
            completed = keys
        conn.execute("UPDATE prep_tasks SET done = ?, completed_steps_json = ? WHERE id = ?",
                     (int(bool(keys) and completed == keys), json.dumps(sorted(completed)), task["id"]))
    conn.execute("DROP TABLE prep_step_done")


def init_db(conn) -> None:
    conn.executescript(SCHEMA_PATH.read_text())
    _add_column(conn, "prep_tasks", "completed_steps_json", "TEXT NOT NULL DEFAULT '[]'")
    _add_column(conn, "prep_tasks", "details_json", "TEXT NOT NULL DEFAULT '{}'")
    _add_column(conn, "plans", "hidden", "INTEGER NOT NULL DEFAULT 0")
    _add_column(conn, "plans", "suggestion_json", "TEXT NOT NULL DEFAULT '{}'")
    _add_column(conn, "plans", "status", "TEXT NOT NULL DEFAULT 'active'")
    _add_column(conn, "plan_slots", "cooked", "INTEGER NOT NULL DEFAULT 0")
    _add_column(conn, "grocery_lines", "quantity_override", "TEXT")
    _add_column(conn, "grocery_lines", "name_override", "TEXT")
    _add_column(conn, "grocery_lines", "store", "TEXT NOT NULL DEFAULT ''")
    _add_column(conn, "ingredients", "package_size", "TEXT NOT NULL DEFAULT ''")
    _add_column(conn, "ingredients", "package_unit", "TEXT NOT NULL DEFAULT ''")
    _add_column(conn, "recipes", "dev_notes", "TEXT NOT NULL DEFAULT ''")
    _add_column(conn, "users", "failed_attempts", "INTEGER NOT NULL DEFAULT 0")
    _add_column(conn, "users", "locked_until", "TEXT")
    _add_column(conn, "prep_step_feedback", "category", "TEXT NOT NULL DEFAULT ''")
    migrate_prep_completion(conn)
    from app.db.seed import apply_seeds

    apply_seeds(conn)
    conn.commit()


def now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


@contextmanager
def transaction(conn):
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
