-- Dinnerdesk runtime. Catalog recipes: household_id IS NULL (read-only over HTTP).

CREATE TABLE IF NOT EXISTS households (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  prefs_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_name TEXT NOT NULL UNIQUE,
  aliases_json TEXT NOT NULL DEFAULT '[]',
  aisle TEXT NOT NULL DEFAULT 'other',
  default_unit TEXT NOT NULL DEFAULT '',
  package_size TEXT NOT NULL DEFAULT '',
  package_unit TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER REFERENCES households(id),
  slug TEXT,
  name TEXT NOT NULL,
  servings INTEGER NOT NULL DEFAULT 4,
  cooking_minutes INTEGER,
  instructions_json TEXT NOT NULL DEFAULT '[]',
  cookware_json TEXT NOT NULL DEFAULT '[]',
  source_url TEXT NOT NULL DEFAULT '',
  provenance_json TEXT NOT NULL DEFAULT '{}',
  photo_path TEXT NOT NULL DEFAULT '',
  dev_notes TEXT NOT NULL DEFAULT '',
  parent_recipe_id INTEGER REFERENCES recipes(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS recipes_household ON recipes(household_id);
CREATE INDEX IF NOT EXISTS recipes_name ON recipes(name);

CREATE TABLE IF NOT EXISTS household_favorites (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS household_try_later (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id),
  quantity TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS recipe_ingredients_recipe ON recipe_ingredients(recipe_id);

CREATE TABLE IF NOT EXISTS recipe_tags (
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  PRIMARY KEY (recipe_id, tag)
);

CREATE TABLE IF NOT EXISTS plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id),
  start_date TEXT NOT NULL,
  days INTEGER NOT NULL DEFAULT 7,
  title TEXT NOT NULL DEFAULT 'This week',
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS plans_household ON plans(household_id);

CREATE TABLE IF NOT EXISTS plan_slots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  day_index INTEGER,
  meal_type TEXT NOT NULL DEFAULT 'dinner',
  recipe_id INTEGER NOT NULL REFERENCES recipes(id),
  servings INTEGER,
  notes TEXT NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  cooked INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS plan_slots_plan ON plan_slots(plan_id);

CREATE TABLE IF NOT EXISTS grocery_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  ingredient_id INTEGER REFERENCES ingredients(id),
  quantity TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT '',
  aisle TEXT NOT NULL DEFAULT 'other',
  store TEXT NOT NULL DEFAULT '',
  checked INTEGER NOT NULL DEFAULT 0,
  from_pantry INTEGER NOT NULL DEFAULT 0,
  never_shop INTEGER NOT NULL DEFAULT 0,
  custom_text TEXT,
  source_slots_json TEXT NOT NULL DEFAULT '[]'
);

CREATE INDEX IF NOT EXISTS grocery_lines_plan ON grocery_lines(plan_id);

CREATE TABLE IF NOT EXISTS pantry_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id),
  ingredient_id INTEGER REFERENCES ingredients(id),
  name TEXT NOT NULL,
  quantity TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT '',
  have INTEGER NOT NULL DEFAULT 1,
  never_shop INTEGER NOT NULL DEFAULT 0,
  zone TEXT NOT NULL DEFAULT 'dry'
);

CREATE INDEX IF NOT EXISTS pantry_household ON pantry_items(household_id);

CREATE TABLE IF NOT EXISTS household_overrides (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  from_name TEXT NOT NULL,
  to_name TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS overrides_household ON household_overrides(household_id);

CREATE TABLE IF NOT EXISTS household_recipe_edits (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  servings INTEGER,
  cooking_minutes INTEGER,
  instructions_json TEXT NOT NULL DEFAULT '[]',
  cookware_json TEXT NOT NULL DEFAULT '[]',
  ingredients_json TEXT NOT NULL DEFAULT '[]',
  updated_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS household_hidden_recipes (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id)
);

-- 👍/👎 on a meal from the plan. -1 = never suggest again, 1 = suggest more like it.
CREATE TABLE IF NOT EXISTS household_meal_ratings (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating IN (-1, 1)),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id)
);

-- 👍/👎 on a single prep step: was it useful to do ahead? Logged for review only; it never
-- hides a step. step_key = hash of the wording; category = the prep heading it was shown under;
-- auto = 1 when the app picked the step, 0 when the recipe tagged it Prep.
CREATE TABLE IF NOT EXISTS prep_step_feedback (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  step_key TEXT NOT NULL,
  step_text TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  auto INTEGER NOT NULL DEFAULT 1,
  rating INTEGER NOT NULL CHECK (rating IN (-1, 1)),
  reason TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL,
  PRIMARY KEY (household_id, recipe_id, step_key)
);

CREATE TABLE IF NOT EXISTS prep_tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  done INTEGER NOT NULL DEFAULT 0,
  linked_slots_json TEXT NOT NULL DEFAULT '[]',
  sort INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS prep_plan ON prep_tasks(plan_id);

CREATE TABLE IF NOT EXISTS recipe_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  photo_path TEXT NOT NULL DEFAULT '',
  rating INTEGER,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS submissions_recipe ON recipe_submissions(recipe_id);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS users_household ON users(household_id);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS household_invites (
  token TEXT PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  invited_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  used_by INTEGER REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS invites_household ON household_invites(household_id);

-- One-time "forgot password" links. Only a hash of the token is stored.
CREATE TABLE IF NOT EXISTS password_resets (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT
);

CREATE INDEX IF NOT EXISTS password_resets_user ON password_resets(user_id);

CREATE TABLE IF NOT EXISTS grocery_places (
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  store TEXT NOT NULL DEFAULT '',
  aisle TEXT NOT NULL DEFAULT 'other',
  PRIMARY KEY (household_id, name)
);
