#!/usr/bin/env python3
"""Taste Lab: photo catalog from parent recipes, PostgreSQL labels, static web."""

from __future__ import annotations

import json
import re
import sys

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[1]))
from app.db.database import PgConnection, connect
from app.domain.recipe_photos import photo_allowed
import uuid
from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent
WEB = ROOT / "web"
from app.assets import food_dir
FOOD = food_dir()
HOST = "0.0.0.0"
PORT = 8780
SKIP = {"incomplete", "side", "sauce", "dressing", "meal_component"}



def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def db() -> PgConnection:
    return connect()

def init_db() -> None:
    with db() as con:
        con.executescript(
            """
            CREATE TABLE IF NOT EXISTS taste_people (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              anon_id TEXT UNIQUE NOT NULL,
              account_id TEXT,
              created_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS taste_sessions (
              id TEXT PRIMARY KEY,
              person_id INTEGER NOT NULL REFERENCES taste_people(id),
              created_at TEXT NOT NULL,
              updated_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS taste_events (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              session_id TEXT NOT NULL REFERENCES taste_sessions(id),
              t TEXT NOT NULL,
              kind TEXT NOT NULL,
              body TEXT NOT NULL
            );
            """
        )


def ing_name(ing: dict | str) -> str:
    if isinstance(ing, str):
        return ing.strip()
    return str(ing.get("name") or "").strip()


def group_ids() -> set[str]:
    text = (WEB / "swipe-groups.js").read_text()
    return set(re.findall(r'"(\d+)"', text))


def load_catalog() -> list[dict]:
    from app.taste_lab import catalog_from_db
    with db() as con:
        return catalog_from_db(con)


CATALOG = []


def person_id(con: PgConnection, anon_id: str, account_id: str | None) -> int:
    row = con.execute("SELECT id, account_id FROM taste_people WHERE anon_id = ?", (anon_id,)).fetchone()
    if row:
        if account_id and not row["account_id"]:
            con.execute("UPDATE taste_people SET account_id = ? WHERE id = ?", (account_id, row["id"]))
        return int(row["id"])
    cur = con.execute(
        "INSERT INTO taste_people (anon_id, account_id, created_at) VALUES (?, ?, ?)",
        (anon_id, account_id, now()),
    )
    return int(cur.lastrowid)


def save_event(body: dict) -> str:
    sid = str(body.get("id") or uuid.uuid4())
    anon_id = str(body.get("anon_id") or uuid.uuid4())
    account_id = body.get("account_id") or None
    kind = str(body.get("kind") or "snapshot")
    payload = body.get("body")
    if payload is None:
        payload = {k: v for k, v in body.items() if k not in {"anon_id", "account_id", "kind"}}
        payload["id"] = sid
    t = now()
    with db() as con:
        pid = person_id(con, anon_id, str(account_id) if account_id else None)
        row = con.execute("SELECT id FROM taste_sessions WHERE id = ?", (sid,)).fetchone()
        if row:
            con.execute("UPDATE taste_sessions SET updated_at = ? WHERE id = ?", (t, sid))
        else:
            con.execute(
                "INSERT INTO taste_sessions (id, person_id, created_at, updated_at) VALUES (?, ?, ?, ?)",
                (sid, pid, t, t),
            )
        con.execute(
            "INSERT INTO taste_events (session_id, t, kind, body) VALUES (?, ?, ?, ?)",
            (sid, t, kind, json.dumps(payload, ensure_ascii=False)),
        )
    return sid


def list_sessions() -> list[dict]:
    with db() as con:
        sess = con.execute(
            """
            SELECT s.id, s.created_at, s.updated_at, p.anon_id, p.account_id
            FROM taste_sessions s
            JOIN taste_people p ON p.id = s.person_id
            ORDER BY s.updated_at DESC
            """
        ).fetchall()
        out = []
        for s in sess:
            events = con.execute(
                "SELECT t, kind, body FROM taste_events WHERE session_id = ? ORDER BY id",
                (s["id"],),
            ).fetchall()
            snap = None
            for ev in reversed(events):
                if ev["kind"] == "snapshot":
                    snap = json.loads(ev["body"])
                    break
            if not isinstance(snap, dict):
                raise ValueError(f"Taste session {s['id']} has no valid snapshot")
            snap["id"] = s["id"]
            snap["anon_id"] = s["anon_id"]
            snap["account_id"] = s["account_id"]
            snap["created_at"] = s["created_at"]
            snap["updated_at"] = s["updated_at"]
            snap["event_count"] = len(events)
            out.append(snap)
        return out


def _json(handler: SimpleHTTPRequestHandler, payload: object, status: int = 200) -> None:
    raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.send_header("Access-Control-Allow-Origin", "*")
    handler.end_headers()
    handler.wfile.write(raw)


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB), **kwargs)

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self) -> None:
        path = urlparse(self.path).path
        if path == "/api/catalog":
            rows = load_catalog()
            _json(self, {"recipes": rows, "count": len(rows)})
            return
        if path == "/api/sessions":
            rows = list_sessions()
            _json(self, {"sessions": rows, "count": len(rows)})
            return
        if path.startswith("/food/"):
            name = Path(path).name
            target = FOOD / name
            if target.is_file() and photo_allowed(name):
                data = target.read_bytes()
                types = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp", ".svg": "image/svg+xml"}
                self.send_response(200)
                self.send_header("Content-Type", types.get(target.suffix.lower(), "application/octet-stream"))
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
        super().do_GET()

    def do_POST(self) -> None:
        path = urlparse(self.path).path
        if path != "/api/sessions":
            _json(self, {"error": "not_found"}, 404)
            return
        length = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(length) if length else b"{}"
        try:
            body = json.loads(raw.decode("utf-8") or "{}")
        except json.JSONDecodeError:
            _json(self, {"error": "bad_json"}, 400)
            return
        sid = save_event(body if isinstance(body, dict) else {})
        _json(self, {"ok": True, "id": sid})

    def log_message(self, fmt: str, *args) -> None:
        print(f"{self.address_string()} {fmt % args}")


def main() -> None:
    init_db()
    print(f"Taste Lab  http://127.0.0.1:{PORT}", flush=True)
    print(f"Taste Lab  http://127.0.0.1:{PORT}", flush=True)
    print("Catalog loads from PostgreSQL", flush=True)
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()


if __name__ == "__main__":
    main()
